// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6j-10UPi4N1chkjkRpjOTlH7zIEab6Cw',
    appId: '1:768311536841:ios:ae8b3ba28b9d22005db118',
    messagingSenderId: '768311536841',
    projectId: 'mirutina-visual',
    storageBucket: 'mirutina-visual.firebasestorage.app',
    iosBundleId: 'com.example.miRutinaVisual',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6j-10UPi4N1chkjkRpjOTlH7zIEab6Cw',
    appId: '1:768311536841:ios:ae8b3ba28b9d22005db118',
    messagingSenderId: '768311536841',
    projectId: 'mirutina-visual',
    storageBucket: 'mirutina-visual.firebasestorage.app',
    iosBundleId: 'com.example.miRutinaVisual',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbMSAqSWfuqfGjdNpzzY5JBUd1AqhZt7A',
    appId: '1:768311536841:web:9cad1da19caffe845db118',
    messagingSenderId: '768311536841',
    projectId: 'mirutina-visual',
    authDomain: 'mirutina-visual.firebaseapp.com',
    storageBucket: 'mirutina-visual.firebasestorage.app',
    measurementId: 'G-N2FGPWQ3WF',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbMSAqSWfuqfGjdNpzzY5JBUd1AqhZt7A',
    appId: '1:768311536841:web:540906c02705c89a5db118',
    messagingSenderId: '768311536841',
    projectId: 'mirutina-visual',
    authDomain: 'mirutina-visual.firebaseapp.com',
    storageBucket: 'mirutina-visual.firebasestorage.app',
    measurementId: 'G-SWMEJZ7SWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO09a8-ROp8Q_aEn4zWQfMr8BdPyekqcA',
    appId: '1:768311536841:android:83072258f05ec9de5db118',
    messagingSenderId: '768311536841',
    projectId: 'mirutina-visual',
    storageBucket: 'mirutina-visual.firebasestorage.app',
  );

}